/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use home for the / route. Do not include slashes.
   */
  slug: string;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalMode?: ('auto' | 'custom') | null;
    canonicalUrl?: string | null;
    index?: boolean | null;
    follow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    ogImageAlt?: string | null;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (number | null) | Media;
    twitterImageAlt?: string | null;
    includeInSitemap?: boolean | null;
  };
  /**
   * Sort reusable CMS page blocks here. Visual style remains controlled by the frontend.
   */
  layout: (
    | HeroBlock
    | CommunitiesStripBlock
    | FeaturedCommunitiesBlock
    | FeaturedResidencesBlock
    | LifestyleBlock
    | TestimonialsBlock
    | AmenitiesBlock
    | OwnerIntroBlock
    | LeadCaptureBlock
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Optional plain section ID without #.
   */
  anchorId?: string | null;
  backgroundImage: {
    /**
     * Full-width landscape, at least 2000px wide.
     */
    image: number | Media;
    /**
     * Optional. Falls back to the media alt text.
     */
    altOverride?: string | null;
  };
  backgroundImagePriority?: boolean | null;
  eyebrow: string;
  heading: string;
  headingAccent?: string | null;
  lede: string;
  primaryCta: {
    label: string;
    link: {
      label: string;
      type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
      page?: (number | null) | Page;
      /**
       * Use for existing app routes such as /listings until they are CMS pages.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    ariaLabel?: string | null;
  };
  secondaryCta: {
    label?: string | null;
    link: {
      label?: string | null;
      type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
      page?: (number | null) | Page;
      /**
       * Use for existing app routes such as /listings until they are CMS pages.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    ariaLabel?: string | null;
  };
  showEyebrowMarker?: boolean | null;
  showPrimaryCtaIcon?: boolean | null;
  showSecondaryCta?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CommunitiesStripBlock".
 */
export interface CommunitiesStripBlock {
  anchorId?: string | null;
  /**
   * Selected/query modes are added after communities exist.
   */
  sourceMode?: 'manual' | null;
  /**
   * Recommended: 3 compact community links.
   */
  items?:
    | {
        name: string;
        blurb: string;
        slug: string;
        link: {
          label: string;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use for existing app routes such as /listings until they are CMS pages.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        icon?: 'mapPin' | null;
        id?: string | null;
      }[]
    | null;
  maxItems?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'communitiesStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCommunitiesBlock".
 */
export interface FeaturedCommunitiesBlock {
  anchorId?: string | null;
  header: {
    kicker: string;
    heading: string;
    /**
     * Optional phrase rendered with the existing emphasized style.
     */
    headingAccent?: string | null;
    lede?: string | null;
  };
  /**
   * Selected/query modes are added after communities exist.
   */
  sourceMode?: 'manual' | null;
  /**
   * Community cards. Images should be 16:11.
   */
  manualCommunities?:
    | {
        slug: string;
        name: string;
        locality: string;
        rating: number;
        reviews: number;
        reviewsLabel?: string | null;
        priceRange: string;
        tags?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        residences: number;
        residencesLabel?: string | null;
        nowSelling: number;
        nowSellingLabel?: string | null;
        image: {
          /**
           * Recommended aspect ratio: 16:11.
           */
          image: number | Media;
          /**
           * Optional. Falls back to the media alt text.
           */
          altOverride?: string | null;
        };
        link: {
          label: string;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use for existing app routes such as /listings until they are CMS pages.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  moreLink: {
    label?: string | null;
    link: {
      label?: string | null;
      type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
      page?: (number | null) | Page;
      /**
       * Use for existing app routes such as /listings until they are CMS pages.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    ariaLabel?: string | null;
  };
  emptyStateHeading?: string | null;
  emptyStateBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredCommunities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedResidencesBlock".
 */
export interface FeaturedResidencesBlock {
  anchorId?: string | null;
  header: {
    kicker: string;
    heading: string;
    /**
     * Optional phrase rendered with the existing emphasized style.
     */
    headingAccent?: string | null;
    lede?: string | null;
  };
  /**
   * Selected/query modes are added after listings exist.
   */
  sourceMode?: 'manual' | null;
  /**
   * Residence cards. Images should be 4:3.
   */
  manualListings?:
    | {
        slug: string;
        name: string;
        locality: string;
        price?: number | null;
        priceLabel: string;
        beds: number;
        bedsLabel?: string | null;
        baths: number;
        bathsLabel?: string | null;
        sqft: number;
        sqftLabel?: string | null;
        badge: string;
        image: {
          /**
           * Recommended aspect ratio: 4:3.
           */
          image: number | Media;
          /**
           * Optional. Falls back to the media alt text.
           */
          altOverride?: string | null;
        };
        link: {
          label: string;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use for existing app routes such as /listings until they are CMS pages.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  cardCtaLabel?: string | null;
  moreLink: {
    label?: string | null;
    link: {
      label?: string | null;
      type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
      page?: (number | null) | Page;
      /**
       * Use for existing app routes such as /listings until they are CMS pages.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    ariaLabel?: string | null;
  };
  emptyStateHeading?: string | null;
  emptyStateBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredResidences';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LifestyleBlock".
 */
export interface LifestyleBlock {
  anchorId?: string | null;
  backgroundImage: {
    /**
     * Full-width landscape, at least 2000px wide.
     */
    image: number | Media;
    /**
     * Optional. Falls back to the media alt text.
     */
    altOverride?: string | null;
  };
  kicker: string;
  heading: string;
  headingAccent?: string | null;
  body: string;
  /**
   * Recommended: 3 tiles. Images should be 3:4.
   */
  tiles?:
    | {
        caption: string;
        image: {
          /**
           * Recommended aspect ratio: 3:4.
           */
          image: number | Media;
          /**
           * Optional. Falls back to the media alt text.
           */
          altOverride?: string | null;
        };
        link: {
          label?: string | null;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use for existing app routes such as /listings until they are CMS pages.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  maxTiles?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'lifestyle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  anchorId?: string | null;
  kicker: string;
  heading: string;
  headingAccent?: string | null;
  headingSuffix?: string | null;
  /**
   * Recommended: 1-8 stories. Portraits should be 4:5.
   */
  stories?:
    | {
        slug: string;
        name: string;
        location: string;
        quote: string;
        portrait: {
          /**
           * Recommended aspect ratio: 4:5.
           */
          image: number | Media;
          /**
           * Optional. Falls back to the media alt text.
           */
          altOverride?: string | null;
        };
        tabAriaLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  carouselAutoPlay?: boolean | null;
  carouselIntervalMs?: number | null;
  previousLabel?: string | null;
  nextLabel?: string | null;
  tabListLabel?: string | null;
  counterSeparator?: string | null;
  emptyStateHeading?: string | null;
  emptyStateBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AmenitiesBlock".
 */
export interface AmenitiesBlock {
  anchorId?: string | null;
  header: {
    kicker: string;
    heading: string;
    /**
     * Optional phrase rendered with the existing emphasized style.
     */
    headingAccent?: string | null;
    lede?: string | null;
  };
  featureImage: {
    /**
     * Large landscape feature image.
     */
    image: number | Media;
    /**
     * Optional. Falls back to the media alt text.
     */
    altOverride?: string | null;
  };
  featureTitle: string;
  featureCaption: string;
  /**
   * Recommended: 1-6 amenity cards.
   */
  amenities?:
    | {
        icon: 'pool' | 'racquet' | 'fitness' | 'dining' | 'trails' | 'calendar';
        title: string;
        blurb: string;
        id?: string | null;
      }[]
    | null;
  emptyStateHeading?: string | null;
  emptyStateBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'amenities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OwnerIntroBlock".
 */
export interface OwnerIntroBlock {
  anchorId?: string | null;
  portrait: {
    /**
     * Recommended aspect ratio: 4:5.
     */
    image: number | Media;
    /**
     * Optional. Falls back to the media alt text.
     */
    altOverride?: string | null;
  };
  portraitBadgeLabel?: string | null;
  kicker: string;
  heading: string;
  headingAccent?: string | null;
  titleLine: string;
  bio: string;
  signature: string;
  /**
   * Recommended: 1-4 credential stats.
   */
  credentials?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ownerIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadCaptureBlock".
 */
export interface LeadCaptureBlock {
  anchorId?: string | null;
  kicker: string;
  heading: string;
  body: string;
  helperNote: {
    icon?: 'waves' | null;
    beforeLinkText?: string | null;
    link: {
      label: string;
      type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
      page?: (number | null) | Page;
      /**
       * Use for existing app routes such as /listings until they are CMS pages.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    afterLinkText?: string | null;
  };
  /**
   * Field set is code-defined; labels and placeholders are editable.
   */
  fields: {
    name: {
      label: string;
      placeholder: string;
      required?: boolean | null;
    };
    email: {
      label: string;
      placeholder: string;
      required?: boolean | null;
    };
    phone: {
      label: string;
      placeholder: string;
      required?: boolean | null;
    };
  };
  submitLabel: string;
  privacyText: string;
  successHeading: string;
  successBody: string;
  errorRequiredMessage: string;
  errorInvalidEmailMessage: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'leadCapture';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalMode?: T;
        canonicalUrl?: T;
        index?: T;
        follow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogImageAlt?: T;
        twitterCard?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        twitterImageAlt?: T;
        includeInSitemap?: T;
      };
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        communitiesStrip?: T | CommunitiesStripBlockSelect<T>;
        featuredCommunities?: T | FeaturedCommunitiesBlockSelect<T>;
        featuredResidences?: T | FeaturedResidencesBlockSelect<T>;
        lifestyle?: T | LifestyleBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        amenities?: T | AmenitiesBlockSelect<T>;
        ownerIntro?: T | OwnerIntroBlockSelect<T>;
        leadCapture?: T | LeadCaptureBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  anchorId?: T;
  backgroundImage?:
    | T
    | {
        image?: T;
        altOverride?: T;
      };
  backgroundImagePriority?: T;
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  lede?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
      };
  showEyebrowMarker?: T;
  showPrimaryCtaIcon?: T;
  showSecondaryCta?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CommunitiesStripBlock_select".
 */
export interface CommunitiesStripBlockSelect<T extends boolean = true> {
  anchorId?: T;
  sourceMode?: T;
  items?:
    | T
    | {
        name?: T;
        blurb?: T;
        slug?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        icon?: T;
        id?: T;
      };
  maxItems?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCommunitiesBlock_select".
 */
export interface FeaturedCommunitiesBlockSelect<T extends boolean = true> {
  anchorId?: T;
  header?:
    | T
    | {
        kicker?: T;
        heading?: T;
        headingAccent?: T;
        lede?: T;
      };
  sourceMode?: T;
  manualCommunities?:
    | T
    | {
        slug?: T;
        name?: T;
        locality?: T;
        rating?: T;
        reviews?: T;
        reviewsLabel?: T;
        priceRange?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        residences?: T;
        residencesLabel?: T;
        nowSelling?: T;
        nowSellingLabel?: T;
        image?:
          | T
          | {
              image?: T;
              altOverride?: T;
            };
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        id?: T;
      };
  moreLink?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
      };
  emptyStateHeading?: T;
  emptyStateBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedResidencesBlock_select".
 */
export interface FeaturedResidencesBlockSelect<T extends boolean = true> {
  anchorId?: T;
  header?:
    | T
    | {
        kicker?: T;
        heading?: T;
        headingAccent?: T;
        lede?: T;
      };
  sourceMode?: T;
  manualListings?:
    | T
    | {
        slug?: T;
        name?: T;
        locality?: T;
        price?: T;
        priceLabel?: T;
        beds?: T;
        bedsLabel?: T;
        baths?: T;
        bathsLabel?: T;
        sqft?: T;
        sqftLabel?: T;
        badge?: T;
        image?:
          | T
          | {
              image?: T;
              altOverride?: T;
            };
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        id?: T;
      };
  cardCtaLabel?: T;
  moreLink?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
      };
  emptyStateHeading?: T;
  emptyStateBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LifestyleBlock_select".
 */
export interface LifestyleBlockSelect<T extends boolean = true> {
  anchorId?: T;
  backgroundImage?:
    | T
    | {
        image?: T;
        altOverride?: T;
      };
  kicker?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  tiles?:
    | T
    | {
        caption?: T;
        image?:
          | T
          | {
              image?: T;
              altOverride?: T;
            };
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        id?: T;
      };
  maxTiles?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  anchorId?: T;
  kicker?: T;
  heading?: T;
  headingAccent?: T;
  headingSuffix?: T;
  stories?:
    | T
    | {
        slug?: T;
        name?: T;
        location?: T;
        quote?: T;
        portrait?:
          | T
          | {
              image?: T;
              altOverride?: T;
            };
        tabAriaLabel?: T;
        id?: T;
      };
  carouselAutoPlay?: T;
  carouselIntervalMs?: T;
  previousLabel?: T;
  nextLabel?: T;
  tabListLabel?: T;
  counterSeparator?: T;
  emptyStateHeading?: T;
  emptyStateBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AmenitiesBlock_select".
 */
export interface AmenitiesBlockSelect<T extends boolean = true> {
  anchorId?: T;
  header?:
    | T
    | {
        kicker?: T;
        heading?: T;
        headingAccent?: T;
        lede?: T;
      };
  featureImage?:
    | T
    | {
        image?: T;
        altOverride?: T;
      };
  featureTitle?: T;
  featureCaption?: T;
  amenities?:
    | T
    | {
        icon?: T;
        title?: T;
        blurb?: T;
        id?: T;
      };
  emptyStateHeading?: T;
  emptyStateBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OwnerIntroBlock_select".
 */
export interface OwnerIntroBlockSelect<T extends boolean = true> {
  anchorId?: T;
  portrait?:
    | T
    | {
        image?: T;
        altOverride?: T;
      };
  portraitBadgeLabel?: T;
  kicker?: T;
  heading?: T;
  headingAccent?: T;
  titleLine?: T;
  bio?: T;
  signature?: T;
  credentials?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadCaptureBlock_select".
 */
export interface LeadCaptureBlockSelect<T extends boolean = true> {
  anchorId?: T;
  kicker?: T;
  heading?: T;
  body?: T;
  helperNote?:
    | T
    | {
        icon?: T;
        beforeLinkText?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        afterLinkText?: T;
      };
  fields?:
    | T
    | {
        name?:
          | T
          | {
              label?: T;
              placeholder?: T;
              required?: T;
            };
        email?:
          | T
          | {
              label?: T;
              placeholder?: T;
              required?: T;
            };
        phone?:
          | T
          | {
              label?: T;
              placeholder?: T;
              required?: T;
            };
      };
  submitLabel?: T;
  privacyText?: T;
  successHeading?: T;
  successBody?: T;
  errorRequiredMessage?: T;
  errorInvalidEmailMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  brandHomeLink: {
    label: string;
    type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
    page?: (number | null) | Page;
    /**
     * Use for existing app routes such as /listings until they are CMS pages.
     */
    customUrl?: string | null;
    /**
     * Examples: #lead, /#lead.
     */
    anchor?: string | null;
    phone?: string | null;
    email?: string | null;
    newTab?: boolean | null;
    ariaLabel?: string | null;
  };
  brandLabel: string;
  brandMarkAlt?: string | null;
  navItems?:
    | {
        label: string;
        link: {
          label: string;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use for existing app routes such as /listings until they are CMS pages.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        ariaLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  primaryCta: {
    label: string;
    link: {
      label: string;
      type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
      page?: (number | null) | Page;
      /**
       * Use for existing app routes such as /listings until they are CMS pages.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    ariaLabel?: string | null;
  };
  mobileMenuLabel: string;
  mobileMenuCloseLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brandName: string;
  brandAccentText?: string | null;
  brandBlurb: string;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              link: {
                label: string;
                type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
                page?: (number | null) | Page;
                /**
                 * Use for existing app routes such as /listings until they are CMS pages.
                 */
                customUrl?: string | null;
                /**
                 * Examples: #lead, /#lead.
                 */
                anchor?: string | null;
                phone?: string | null;
                email?: string | null;
                newTab?: boolean | null;
                ariaLabel?: string | null;
              };
              ariaLabel?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bottomLeftText: string;
  bottomRightLinks?:
    | {
        link: {
          label: string;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use for existing app routes such as /listings until they are CMS pages.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  bottomRightTextFallback?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  brandHomeLink?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        customUrl?: T;
        anchor?: T;
        phone?: T;
        email?: T;
        newTab?: T;
        ariaLabel?: T;
      };
  brandLabel?: T;
  brandMarkAlt?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
        id?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
      };
  mobileMenuLabel?: T;
  mobileMenuCloseLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandName?: T;
  brandAccentText?: T;
  brandBlurb?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    customUrl?: T;
                    anchor?: T;
                    phone?: T;
                    email?: T;
                    newTab?: T;
                    ariaLabel?: T;
                  };
              ariaLabel?: T;
              id?: T;
            };
        id?: T;
      };
  bottomLeftText?: T;
  bottomRightLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        id?: T;
      };
  bottomRightTextFallback?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}