/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    brokers: Broker;
    areas: Area;
    listings: Listing;
    leads: Lead;
    'sync-logs': SyncLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    brokers: BrokersSelect<false> | BrokersSelect<true>;
    areas: AreasSelect<false> | AreasSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'sync-logs': SyncLogsSelect<false> | SyncLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'privacy-policy': PrivacyPolicy;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      syncBridgeListings: TaskSyncBridgeListings;
      mirrorListingHero: TaskMirrorListingHero;
      syncLeadToWiseAgent: TaskSyncLeadToWiseAgent;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use home for the / route. Enter a lowercase kebab-case segment.
   */
  slug: string;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalMode?: ('auto' | 'custom') | null;
    canonicalUrl?: string | null;
    index?: boolean | null;
    follow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    ogImageAlt?: string | null;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (number | null) | Media;
    twitterImageAlt?: string | null;
    /**
     * Uncheck to keep this URL out of /sitemap.xml.
     */
    includeInSitemap?: boolean | null;
  };
  /**
   * Sort reusable CMS page blocks here. Visual style remains controlled by the frontend.
   */
  layout: (
    | HeroBlock
    | CommunitiesStripBlock
    | FeaturedCommunitiesBlock
    | FeaturedResidencesBlock
    | LifestyleBlock
    | TestimonialsBlock
    | AmenitiesBlock
    | OwnerIntroBlock
    | LeadCaptureBlock
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Disable to keep this block in the page without rendering it.
   */
  enabled?: boolean | null;
  /**
   * Plain section ID without #, for example featured-listings.
   */
  anchorId?: string | null;
  backgroundImage: {
    /**
     * Full-width landscape, at least 2000px wide.
     */
    image: number | Media;
    /**
     * Optional. Falls back to the media alt text.
     */
    altOverride?: string | null;
  };
  backgroundImagePriority?: boolean | null;
  eyebrow: string;
  heading: string;
  headingAccent?: string | null;
  lede: string;
  primaryCta: {
    label: string;
    link: {
      label?: string | null;
      type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
      page?: (number | null) | Page;
      /**
       * Use a single-leading-slash app route or an HTTP(S) URL.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    ariaLabel?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    link?: {
      label?: string | null;
      type?: ('internal' | 'custom' | 'anchor' | 'phone' | 'email') | null;
      page?: (number | null) | Page;
      /**
       * Use a single-leading-slash app route or an HTTP(S) URL.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    ariaLabel?: string | null;
  };
  showEyebrowMarker?: boolean | null;
  showPrimaryCtaIcon?: boolean | null;
  showSecondaryCta?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CommunitiesStripBlock".
 */
export interface CommunitiesStripBlock {
  /**
   * Disable to keep this block in the page without rendering it.
   */
  enabled?: boolean | null;
  /**
   * Plain section ID without #, for example featured-listings.
   */
  anchorId?: string | null;
  /**
   * Areas mode loads strip items from Areas (kind=community). Edit name/blurb on the Area document.
   */
  sourceMode?: ('areas' | 'manual') | null;
  /**
   * Legacy manual strip items. Prefer Areas collection.
   */
  items?:
    | {
        name: string;
        blurb: string;
        slug: string;
        link: {
          label?: string | null;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use a single-leading-slash app route or an HTTP(S) URL.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        icon?: 'mapPin' | null;
        id?: string | null;
      }[]
    | null;
  /**
   * How many community Areas to show in the strip.
   */
  maxItems?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'communitiesStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCommunitiesBlock".
 */
export interface FeaturedCommunitiesBlock {
  /**
   * Disable to keep this block in the page without rendering it.
   */
  enabled?: boolean | null;
  /**
   * Plain section ID without #, for example featured-listings.
   */
  anchorId?: string | null;
  header: {
    kicker: string;
    heading: string;
    /**
     * Optional phrase rendered with the existing emphasized style.
     */
    headingAccent?: string | null;
    lede?: string | null;
  };
  /**
   * Areas mode loads community cards from Areas (kind=community). Edit blurbs, gallery, and tags there — not here.
   */
  sourceMode?: ('areas' | 'manual') | null;
  /**
   * Legacy manual cards. Prefer Areas collection.
   */
  manualCommunities?:
    | {
        slug: string;
        name: string;
        locality: string;
        priceRange: string;
        tags?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        residences: number;
        residencesLabel?: string | null;
        nowSelling: number;
        nowSellingLabel?: string | null;
        image: {
          /**
           * Recommended aspect ratio: 16:11.
           */
          image: number | Media;
          /**
           * Optional. Falls back to the media alt text.
           */
          altOverride?: string | null;
        };
        link: {
          label?: string | null;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use a single-leading-slash app route or an HTTP(S) URL.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  moreLink?: {
    label?: string | null;
    link?: {
      label?: string | null;
      type?: ('internal' | 'custom' | 'anchor' | 'phone' | 'email') | null;
      page?: (number | null) | Page;
      /**
       * Use a single-leading-slash app route or an HTTP(S) URL.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    ariaLabel?: string | null;
  };
  emptyStateHeading?: string | null;
  emptyStateBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredCommunities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedResidencesBlock".
 */
export interface FeaturedResidencesBlock {
  /**
   * Disable to keep this block in the page without rendering it.
   */
  enabled?: boolean | null;
  /**
   * Plain section ID without #, for example featured-listings.
   */
  anchorId?: string | null;
  header: {
    kicker: string;
    heading: string;
    /**
     * Optional phrase rendered with the existing emphasized style.
     */
    headingAccent?: string | null;
    lede?: string | null;
  };
  /**
   * Reserved for selected/query modes after listings exist.
   */
  sourceMode?: 'manual' | null;
  /**
   * Deprecated. Superseded by the isFeatured flag on listings.
   */
  manualListings?:
    | {
        slug: string;
        name: string;
        locality: string;
        /**
         * Reserved for future sorting; priceLabel is displayed.
         */
        price?: number | null;
        priceLabel: string;
        beds: number;
        bedsLabel?: string | null;
        baths: number;
        bathsLabel?: string | null;
        sqft: number;
        sqftLabel?: string | null;
        badge: string;
        image: {
          /**
           * Recommended aspect ratio: 4:3.
           */
          image: number | Media;
          /**
           * Optional. Falls back to the media alt text.
           */
          altOverride?: string | null;
        };
        link: {
          label?: string | null;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use a single-leading-slash app route or an HTTP(S) URL.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  cardCtaLabel?: string | null;
  moreLink?: {
    label?: string | null;
    link?: {
      label?: string | null;
      type?: ('internal' | 'custom' | 'anchor' | 'phone' | 'email') | null;
      page?: (number | null) | Page;
      /**
       * Use a single-leading-slash app route or an HTTP(S) URL.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    ariaLabel?: string | null;
  };
  emptyStateHeading?: string | null;
  emptyStateBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredResidences';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LifestyleBlock".
 */
export interface LifestyleBlock {
  /**
   * Disable to keep this block in the page without rendering it.
   */
  enabled?: boolean | null;
  /**
   * Plain section ID without #, for example featured-listings.
   */
  anchorId?: string | null;
  backgroundImage: {
    /**
     * Full-width landscape, at least 2000px wide.
     */
    image: number | Media;
    /**
     * Optional. Falls back to the media alt text.
     */
    altOverride?: string | null;
  };
  kicker: string;
  heading: string;
  headingAccent?: string | null;
  body: string;
  /**
   * Recommended: 3 tiles. Images should be 3:4.
   */
  tiles: {
    caption: string;
    image: {
      /**
       * Recommended aspect ratio: 3:4.
       */
      image: number | Media;
      /**
       * Optional. Falls back to the media alt text.
       */
      altOverride?: string | null;
    };
    link?: {
      label?: string | null;
      type?: ('internal' | 'custom' | 'anchor' | 'phone' | 'email') | null;
      page?: (number | null) | Page;
      /**
       * Use a single-leading-slash app route or an HTTP(S) URL.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    id?: string | null;
  }[];
  maxTiles?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'lifestyle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Disable to keep this block in the page without rendering it.
   */
  enabled?: boolean | null;
  /**
   * Plain section ID without #, for example featured-listings.
   */
  anchorId?: string | null;
  kicker: string;
  heading: string;
  headingAccent?: string | null;
  headingSuffix?: string | null;
  /**
   * Recommended: 1-8 stories. Portraits should be 4:5.
   */
  stories: {
    slug: string;
    name: string;
    quote: string;
    portrait: {
      /**
       * Recommended aspect ratio: 4:5.
       */
      image: number | Media;
      /**
       * Optional. Falls back to the media alt text.
       */
      altOverride?: string | null;
    };
    tabAriaLabel?: string | null;
    id?: string | null;
  }[];
  carouselAutoPlay?: boolean | null;
  carouselIntervalMs?: number | null;
  previousLabel?: string | null;
  nextLabel?: string | null;
  tabListLabel?: string | null;
  counterSeparator?: string | null;
  emptyStateHeading?: string | null;
  emptyStateBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AmenitiesBlock".
 */
export interface AmenitiesBlock {
  /**
   * Disable to keep this block in the page without rendering it.
   */
  enabled?: boolean | null;
  /**
   * Plain section ID without #, for example featured-listings.
   */
  anchorId?: string | null;
  header: {
    kicker: string;
    heading: string;
    /**
     * Optional phrase rendered with the existing emphasized style.
     */
    headingAccent?: string | null;
    lede?: string | null;
  };
  featureImage: {
    /**
     * Large landscape feature image.
     */
    image: number | Media;
    /**
     * Optional. Falls back to the media alt text.
     */
    altOverride?: string | null;
  };
  featureTitle: string;
  featureCaption: string;
  /**
   * Recommended: 1-6 amenity cards.
   */
  amenities: {
    icon: 'pool' | 'racquet' | 'fitness' | 'dining' | 'trails' | 'calendar';
    title: string;
    blurb: string;
    id?: string | null;
  }[];
  emptyStateHeading?: string | null;
  emptyStateBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'amenities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OwnerIntroBlock".
 */
export interface OwnerIntroBlock {
  /**
   * Disable to keep this block in the page without rendering it.
   */
  enabled?: boolean | null;
  /**
   * Plain section ID without #, for example featured-listings.
   */
  anchorId?: string | null;
  portrait: {
    /**
     * Recommended aspect ratio: 4:5.
     */
    image: number | Media;
    /**
     * Optional. Falls back to the media alt text.
     */
    altOverride?: string | null;
  };
  portraitBadgeLabel?: string | null;
  kicker: string;
  heading: string;
  headingAccent?: string | null;
  titleLine: string;
  bio: string;
  signature: string;
  /**
   * Optional: up to 4 credential stats.
   */
  credentials?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ownerIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadCaptureBlock".
 */
export interface LeadCaptureBlock {
  /**
   * Disable to keep this block in the page without rendering it.
   */
  enabled?: boolean | null;
  /**
   * Plain section ID without #, for example featured-listings.
   */
  anchorId?: string | null;
  kicker: string;
  heading: string;
  body: string;
  helperNote: {
    icon?: 'waves' | null;
    beforeLinkText?: string | null;
    link: {
      label: string;
      type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
      page?: (number | null) | Page;
      /**
       * Use a single-leading-slash app route or an HTTP(S) URL.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    afterLinkText?: string | null;
  };
  /**
   * Field set is code-defined; labels and placeholders are editable.
   */
  fields: {
    firstName: {
      label: string;
      placeholder: string;
      required?: boolean | null;
    };
    lastName: {
      label: string;
      placeholder: string;
      required?: boolean | null;
    };
    email: {
      label: string;
      placeholder: string;
      required?: boolean | null;
    };
    phone: {
      label: string;
      placeholder: string;
      required?: boolean | null;
    };
  };
  submitLabel: string;
  privacyText: string;
  successHeading: string;
  successBody: string;
  errorRequiredMessage: string;
  errorInvalidEmailMessage: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'leadCapture';
}
/**
 * Agent/broker identity for community concierge and listing PDP asides.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brokers".
 */
export interface Broker {
  id: number;
  /**
   * Display name, e.g. Eleanor Voss.
   */
  name: string;
  /**
   * Lowercase kebab-case, e.g. eleanor-voss.
   */
  slug: string;
  /**
   * Role line, e.g. Broker & Owner.
   */
  title: string;
  /**
   * Brokerage name. PDP joins with ·; community aside joins with ,.
   */
  brokerage: string;
  /**
   * `{community}` is replaced with the area name; omit the token for a fixed label.
   */
  conciergeLabel?: string | null;
  /**
   * Square portrait.
   */
  headshot?: (number | null) | Media;
  /**
   * Display format; tel: href is derived at read time.
   */
  phone?: string | null;
  email?: string | null;
  /**
   * Plain text (not rich text).
   */
  bio?: string | null;
  signature?: string | null;
  /**
   * Optional: up to 3 credential stats.
   */
  credentials?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display-only, manually maintained. Leave empty to hide.
   */
  rating?: number | null;
  /**
   * Display-only, manually maintained. Leave empty to hide.
   */
  reviewCount?: number | null;
  /**
   * Rendered as "N min". Leave empty to hide.
   */
  avgResponseMinutes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * MLS sync targets. Community Areas power homepage community cards/strip and detail pages; cities feed listings filters.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas".
 */
export interface Area {
  id: number;
  /**
   * Lowercase kebab-case, e.g. bonita-bay.
   */
  slug: string;
  name: string;
  kind: 'community' | 'city';
  /**
   * Display city, e.g. Bonita Springs.
   */
  city: string;
  /**
   * e.g. Lee or Collier.
   */
  county: string;
  /**
   * Exact NABOR MLSAreaMajor value (uppercase), used with MlsStatus eq Active.
   */
  mlsAreaMajor: string;
  syncEnabled?: boolean | null;
  /**
   * Updated by the Bridge sync job.
   */
  lastSyncedAt?: string | null;
  /**
   * Community concierge. Cities may set a fallback too.
   */
  broker?: (number | null) | Broker;
  /**
   * Homepage strip line, e.g. "Bonita Springs · golf, marina & a private Gulf beach park".
   */
  blurb?: string | null;
  /**
   * Detail-page intro under the H1. Distinct from `blurb`, the one-line homepage strip label.
   */
  detailBlurb?: string | null;
  /**
   * Card subtitle under the name, e.g. "Bonita Springs · private Gulf beach park".
   */
  locality?: string | null;
  /**
   * Display price band for cards, e.g. "From the $400s – $5M+".
   */
  priceRange?: string | null;
  /**
   * Total homes in the community (not active listings). Shown on featured cards.
   */
  totalResidences?: number | null;
  /**
   * Total photo count for the gallery "All N photos" button.
   */
  photoCount?: number | null;
  phone?: string | null;
  /**
   * Overview fact strip on the community detail page.
   */
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * First image is used on homepage community cards. Recommended 16:11.
   */
  gallery?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  about?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Amenity titles also appear as tags on homepage community cards.
   */
  amenities?:
    | {
        icon:
          | 'golf'
          | 'marina'
          | 'beach'
          | 'racquet'
          | 'fitness'
          | 'dining'
          | 'trails'
          | 'pool'
          | 'club'
          | 'spa'
          | 'gate'
          | 'dog'
          | 'pickleball'
          | 'tennis'
          | 'boating'
          | 'kayak'
          | 'playground'
          | 'concierge'
          | 'valet'
          | 'business-center'
          | 'library'
          | 'garden'
          | 'bike'
          | 'theater'
          | 'sauna'
          | 'yoga'
          | 'cafe'
          | 'bar'
          | 'events'
          | 'card-room';
        title: string;
        id?: string | null;
      }[]
    | null;
  clubs?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Similar nearby communities rail on the detail page.
   */
  similar?: (number | Area)[] | null;
  /**
   * Homes this brokerage has sold in this community. Manually maintained — not derived from MLS data. Leave empty to hide the tile.
   */
  soldCount?: number | null;
  /**
   * Overrides only, and only meaningful for community Areas (cities have no detail page). Blank fields are generated from the name, city and blurb.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalMode?: ('auto' | 'custom') | null;
    canonicalUrl?: string | null;
    index?: boolean | null;
    follow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    ogImageAlt?: string | null;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (number | null) | Media;
    twitterImageAlt?: string | null;
    /**
     * Uncheck to keep this URL out of /sitemap.xml.
     */
    includeInSitemap?: boolean | null;
  };
  /**
   * Written by sync from active listings in this area.
   */
  activeCount?: number | null;
  priceMin?: number | null;
  priceMax?: number | null;
  avgPricePerSqft?: number | null;
  bedsMin?: number | null;
  bedsMax?: number | null;
  sqftMin?: number | null;
  sqftMax?: number | null;
  hoaMin?: number | null;
  hoaMax?: number | null;
  yearBuiltMin?: number | null;
  yearBuiltMax?: number | null;
  is55Plus?: boolean | null;
  isGated?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * MLS listings ingested from Bridge. Public read for the web listings PLP/PDP.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  /**
   * Bridge/RESO ListingKey — upsert key for sync.
   */
  listingKey: string;
  mlsId: string;
  /**
   * {street}-{city}-fl-{mlsId}
   */
  slug: string;
  area: number | Area;
  /**
   * Optional override for the listing PDP aside. Falls back to the area broker when empty.
   */
  broker?: (number | null) | Broker;
  /**
   * False when delisted; page can stay live, grids hide it.
   */
  isActive?: boolean | null;
  syncedAt?: string | null;
  /**
   * RESO ModificationTimestamp from the feed.
   */
  modificationTimestamp?: string | null;
  fullAddress: string;
  streetAddress?: string | null;
  city: string;
  state?: string | null;
  zip?: string | null;
  /**
   * RESO Latitude — centers the PDP location map.
   */
  latitude?: number | null;
  /**
   * RESO Longitude — centers the PDP location map.
   */
  longitude?: number | null;
  price: number;
  beds?: number | null;
  baths?: number | null;
  sqft?: number | null;
  pricePerSqft?: number | null;
  propertyType?: ('single-family' | 'condo' | 'townhouse' | 'multi-family' | 'villa' | 'land' | 'other') | null;
  mlsStatus: 'active' | 'pending' | 'under-contract' | 'sold' | 'coming-soon';
  features?: ('waterfront' | 'private-pool' | 'golf' | 'gated' | '55-plus')[] | null;
  yearBuilt?: number | null;
  lotSqft?: number | null;
  taxesYearly?: number | null;
  hoaMonthly?: number | null;
  /**
   * Primary photo mirrored to R2 by the hero job.
   */
  heroImage?: (number | null) | Media;
  /**
   * Bridge MediaKey of the mirrored hero — skip re-download when unchanged.
   */
  heroMediaKey?: string | null;
  gallery?:
    | {
        /**
         * Bridge CDN URL — always present.
         */
        url: string;
        /**
         * Change-detection key from Bridge MediaKey.
         */
        mediaKey: string;
        order: number;
        /**
         * Unused in Phase 1; reserved for full-gallery mirror.
         */
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  publicRemarks?: string | null;
  listAgentName?: string | null;
  listOfficeName?: string | null;
  interiorSpecs?: {
    interiorFeatures?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    appliances?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    flooring?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    heating?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    cooling?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    laundryFeatures?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  exteriorSpecs?: {
    roof?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    constructionMaterials?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    parkingFeatures?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    poolFeatures?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    lotFeatures?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    sewer?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    waterSource?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Optional marketing label. Sync never writes this.
   */
  badge?: string | null;
  /**
   * Show on the homepage curated residences rail. Sync never writes this.
   */
  isFeatured?: boolean | null;
  /**
   * Marketing price tier — not an MLS field.
   */
  isEstate?: boolean | null;
  neighborhoodBlurb?: string | null;
  highlights?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Author-only room list; hide on PDP when empty.
   */
  floorPlan?:
    | {
        area: string;
        name: string;
        note?: string | null;
        tone?: ('primary' | 'common') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Overrides only. Anything left blank is generated from the address, community, price and specs.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalMode?: ('auto' | 'custom') | null;
    canonicalUrl?: string | null;
    index?: boolean | null;
    follow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    ogImageAlt?: string | null;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (number | null) | Media;
    twitterImageAlt?: string | null;
    /**
     * Uncheck to keep this URL out of /sitemap.xml.
     */
    includeInSitemap?: boolean | null;
  };
  /**
   * Full RESO record for debugging / later field extraction.
   */
  rawData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Website lead submissions. Source of truth — Wise Agent sync is an outbound mirror, so a failed sync never loses a lead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  /**
   * Sent to Wise Agent in the lead email, not as a contact field.
   */
  message?: string | null;
  /**
   * Determines the Wise Agent Source. Do not repurpose existing values.
   */
  formType: 'tour' | 'shortlist';
  /**
   * Which component submitted. Reporting only.
   */
  surface:
    | 'concierge-cta'
    | 'page-lead-capture'
    | 'property-tour-form'
    | 'community-tour-band'
    | 'community-agent-aside';
  pageUrl?: string | null;
  /**
   * Resolved from the submitted community slug.
   */
  area?: (number | null) | Area;
  /**
   * Resolved from the submitted listing slug.
   */
  listing?: (number | null) | Listing;
  /**
   * Written by the syncLeadToWiseAgent job, which emails the Wise Agent lead-capture address. Read-only in practice.
   */
  crm: {
    /**
     * synced means the mail provider accepted the lead email — email parsing sends no confirmation back. skipped means no lead-capture address or mail transport was configured when the job ran. A failed sync can be retried below; bulk replays use `leads:resync`.
     */
    status: 'pending' | 'synced' | 'failed' | 'skipped';
    syncedAt?: string | null;
    error?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Bridge MLS sync run history. Zero-listing areas are flagged as warnings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-logs".
 */
export interface SyncLog {
  id: number;
  runAt: string;
  trigger: 'cron' | 'manual';
  durationMs?: number | null;
  status: 'success' | 'warning' | 'error';
  /**
   * High-level summary, e.g. zero-listing warnings.
   */
  message?: string | null;
  areas?:
    | {
        area: number | Area;
        areaSlug?: string | null;
        fetched: number;
        created: number;
        updated: number;
        deactivated: number;
        warnings?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        errors?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'syncBridgeListings' | 'mirrorListingHero' | 'syncLeadToWiseAgent';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'syncBridgeListings' | 'mirrorListingHero' | 'syncLeadToWiseAgent') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'brokers';
        value: number | Broker;
      } | null)
    | ({
        relationTo: 'areas';
        value: number | Area;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'sync-logs';
        value: number | SyncLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalMode?: T;
        canonicalUrl?: T;
        index?: T;
        follow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogImageAlt?: T;
        twitterCard?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        twitterImageAlt?: T;
        includeInSitemap?: T;
      };
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        communitiesStrip?: T | CommunitiesStripBlockSelect<T>;
        featuredCommunities?: T | FeaturedCommunitiesBlockSelect<T>;
        featuredResidences?: T | FeaturedResidencesBlockSelect<T>;
        lifestyle?: T | LifestyleBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        amenities?: T | AmenitiesBlockSelect<T>;
        ownerIntro?: T | OwnerIntroBlockSelect<T>;
        leadCapture?: T | LeadCaptureBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  enabled?: T;
  anchorId?: T;
  backgroundImage?:
    | T
    | {
        image?: T;
        altOverride?: T;
      };
  backgroundImagePriority?: T;
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  lede?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
      };
  showEyebrowMarker?: T;
  showPrimaryCtaIcon?: T;
  showSecondaryCta?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CommunitiesStripBlock_select".
 */
export interface CommunitiesStripBlockSelect<T extends boolean = true> {
  enabled?: T;
  anchorId?: T;
  sourceMode?: T;
  items?:
    | T
    | {
        name?: T;
        blurb?: T;
        slug?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        icon?: T;
        id?: T;
      };
  maxItems?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCommunitiesBlock_select".
 */
export interface FeaturedCommunitiesBlockSelect<T extends boolean = true> {
  enabled?: T;
  anchorId?: T;
  header?:
    | T
    | {
        kicker?: T;
        heading?: T;
        headingAccent?: T;
        lede?: T;
      };
  sourceMode?: T;
  manualCommunities?:
    | T
    | {
        slug?: T;
        name?: T;
        locality?: T;
        priceRange?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        residences?: T;
        residencesLabel?: T;
        nowSelling?: T;
        nowSellingLabel?: T;
        image?:
          | T
          | {
              image?: T;
              altOverride?: T;
            };
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        id?: T;
      };
  moreLink?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
      };
  emptyStateHeading?: T;
  emptyStateBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedResidencesBlock_select".
 */
export interface FeaturedResidencesBlockSelect<T extends boolean = true> {
  enabled?: T;
  anchorId?: T;
  header?:
    | T
    | {
        kicker?: T;
        heading?: T;
        headingAccent?: T;
        lede?: T;
      };
  sourceMode?: T;
  manualListings?:
    | T
    | {
        slug?: T;
        name?: T;
        locality?: T;
        price?: T;
        priceLabel?: T;
        beds?: T;
        bedsLabel?: T;
        baths?: T;
        bathsLabel?: T;
        sqft?: T;
        sqftLabel?: T;
        badge?: T;
        image?:
          | T
          | {
              image?: T;
              altOverride?: T;
            };
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        id?: T;
      };
  cardCtaLabel?: T;
  moreLink?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
      };
  emptyStateHeading?: T;
  emptyStateBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LifestyleBlock_select".
 */
export interface LifestyleBlockSelect<T extends boolean = true> {
  enabled?: T;
  anchorId?: T;
  backgroundImage?:
    | T
    | {
        image?: T;
        altOverride?: T;
      };
  kicker?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  tiles?:
    | T
    | {
        caption?: T;
        image?:
          | T
          | {
              image?: T;
              altOverride?: T;
            };
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        id?: T;
      };
  maxTiles?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  enabled?: T;
  anchorId?: T;
  kicker?: T;
  heading?: T;
  headingAccent?: T;
  headingSuffix?: T;
  stories?:
    | T
    | {
        slug?: T;
        name?: T;
        quote?: T;
        portrait?:
          | T
          | {
              image?: T;
              altOverride?: T;
            };
        tabAriaLabel?: T;
        id?: T;
      };
  carouselAutoPlay?: T;
  carouselIntervalMs?: T;
  previousLabel?: T;
  nextLabel?: T;
  tabListLabel?: T;
  counterSeparator?: T;
  emptyStateHeading?: T;
  emptyStateBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AmenitiesBlock_select".
 */
export interface AmenitiesBlockSelect<T extends boolean = true> {
  enabled?: T;
  anchorId?: T;
  header?:
    | T
    | {
        kicker?: T;
        heading?: T;
        headingAccent?: T;
        lede?: T;
      };
  featureImage?:
    | T
    | {
        image?: T;
        altOverride?: T;
      };
  featureTitle?: T;
  featureCaption?: T;
  amenities?:
    | T
    | {
        icon?: T;
        title?: T;
        blurb?: T;
        id?: T;
      };
  emptyStateHeading?: T;
  emptyStateBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OwnerIntroBlock_select".
 */
export interface OwnerIntroBlockSelect<T extends boolean = true> {
  enabled?: T;
  anchorId?: T;
  portrait?:
    | T
    | {
        image?: T;
        altOverride?: T;
      };
  portraitBadgeLabel?: T;
  kicker?: T;
  heading?: T;
  headingAccent?: T;
  titleLine?: T;
  bio?: T;
  signature?: T;
  credentials?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadCaptureBlock_select".
 */
export interface LeadCaptureBlockSelect<T extends boolean = true> {
  enabled?: T;
  anchorId?: T;
  kicker?: T;
  heading?: T;
  body?: T;
  helperNote?:
    | T
    | {
        icon?: T;
        beforeLinkText?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        afterLinkText?: T;
      };
  fields?:
    | T
    | {
        firstName?:
          | T
          | {
              label?: T;
              placeholder?: T;
              required?: T;
            };
        lastName?:
          | T
          | {
              label?: T;
              placeholder?: T;
              required?: T;
            };
        email?:
          | T
          | {
              label?: T;
              placeholder?: T;
              required?: T;
            };
        phone?:
          | T
          | {
              label?: T;
              placeholder?: T;
              required?: T;
            };
      };
  submitLabel?: T;
  privacyText?: T;
  successHeading?: T;
  successBody?: T;
  errorRequiredMessage?: T;
  errorInvalidEmailMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brokers_select".
 */
export interface BrokersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  brokerage?: T;
  conciergeLabel?: T;
  headshot?: T;
  phone?: T;
  email?: T;
  bio?: T;
  signature?: T;
  credentials?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  rating?: T;
  reviewCount?: T;
  avgResponseMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas_select".
 */
export interface AreasSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  kind?: T;
  city?: T;
  county?: T;
  mlsAreaMajor?: T;
  syncEnabled?: T;
  lastSyncedAt?: T;
  broker?: T;
  blurb?: T;
  detailBlurb?: T;
  locality?: T;
  priceRange?: T;
  totalResidences?: T;
  photoCount?: T;
  phone?: T;
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  about?: T;
  amenities?:
    | T
    | {
        icon?: T;
        title?: T;
        id?: T;
      };
  clubs?:
    | T
    | {
        item?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  similar?: T;
  soldCount?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalMode?: T;
        canonicalUrl?: T;
        index?: T;
        follow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogImageAlt?: T;
        twitterCard?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        twitterImageAlt?: T;
        includeInSitemap?: T;
      };
  activeCount?: T;
  priceMin?: T;
  priceMax?: T;
  avgPricePerSqft?: T;
  bedsMin?: T;
  bedsMax?: T;
  sqftMin?: T;
  sqftMax?: T;
  hoaMin?: T;
  hoaMax?: T;
  yearBuiltMin?: T;
  yearBuiltMax?: T;
  is55Plus?: T;
  isGated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  listingKey?: T;
  mlsId?: T;
  slug?: T;
  area?: T;
  broker?: T;
  isActive?: T;
  syncedAt?: T;
  modificationTimestamp?: T;
  fullAddress?: T;
  streetAddress?: T;
  city?: T;
  state?: T;
  zip?: T;
  latitude?: T;
  longitude?: T;
  price?: T;
  beds?: T;
  baths?: T;
  sqft?: T;
  pricePerSqft?: T;
  propertyType?: T;
  mlsStatus?: T;
  features?: T;
  yearBuilt?: T;
  lotSqft?: T;
  taxesYearly?: T;
  hoaMonthly?: T;
  heroImage?: T;
  heroMediaKey?: T;
  gallery?:
    | T
    | {
        url?: T;
        mediaKey?: T;
        order?: T;
        media?: T;
        id?: T;
      };
  publicRemarks?: T;
  listAgentName?: T;
  listOfficeName?: T;
  interiorSpecs?:
    | T
    | {
        interiorFeatures?:
          | T
          | {
              item?: T;
              id?: T;
            };
        appliances?:
          | T
          | {
              item?: T;
              id?: T;
            };
        flooring?:
          | T
          | {
              item?: T;
              id?: T;
            };
        heating?:
          | T
          | {
              item?: T;
              id?: T;
            };
        cooling?:
          | T
          | {
              item?: T;
              id?: T;
            };
        laundryFeatures?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  exteriorSpecs?:
    | T
    | {
        roof?:
          | T
          | {
              item?: T;
              id?: T;
            };
        constructionMaterials?:
          | T
          | {
              item?: T;
              id?: T;
            };
        parkingFeatures?:
          | T
          | {
              item?: T;
              id?: T;
            };
        poolFeatures?:
          | T
          | {
              item?: T;
              id?: T;
            };
        lotFeatures?:
          | T
          | {
              item?: T;
              id?: T;
            };
        sewer?:
          | T
          | {
              item?: T;
              id?: T;
            };
        waterSource?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  badge?: T;
  isFeatured?: T;
  isEstate?: T;
  neighborhoodBlurb?: T;
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  floorPlan?:
    | T
    | {
        area?: T;
        name?: T;
        note?: T;
        tone?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalMode?: T;
        canonicalUrl?: T;
        index?: T;
        follow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogImageAlt?: T;
        twitterCard?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        twitterImageAlt?: T;
        includeInSitemap?: T;
      };
  rawData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  message?: T;
  formType?: T;
  surface?: T;
  pageUrl?: T;
  area?: T;
  listing?: T;
  crm?:
    | T
    | {
        status?: T;
        syncedAt?: T;
        error?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-logs_select".
 */
export interface SyncLogsSelect<T extends boolean = true> {
  runAt?: T;
  trigger?: T;
  durationMs?: T;
  status?: T;
  message?: T;
  areas?:
    | T
    | {
        area?: T;
        areaSlug?: T;
        fetched?: T;
        created?: T;
        updated?: T;
        deactivated?: T;
        warnings?:
          | T
          | {
              item?: T;
              id?: T;
            };
        errors?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Business identity used for structured data (JSON-LD) and default social sharing tags. Keep the name, address and phone identical to the Google Business Profile.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Public brand name, e.g. "55 Living Team".
   */
  name: string;
  /**
   * Registered entity name, if it differs from the brand.
   */
  legalName?: string | null;
  /**
   * Falls back to the built-in site description when blank.
   */
  description?: string | null;
  /**
   * Florida real estate license number.
   */
  licenseNumber?: string | null;
  /**
   * schema.org priceRange, e.g. "$$$$".
   */
  priceRange?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: {
    streetAddress?: string | null;
    addressLocality?: string | null;
    addressRegion?: string | null;
    postalCode?: string | null;
    addressCountry?: string | null;
  };
  /**
   * Office coordinates. Emitted only when both are set.
   */
  geo?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  openingHours?:
    | {
        days: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday')[];
        /**
         * 24-hour HH:MM, e.g. 09:00.
         */
        opens: string;
        /**
         * 24-hour HH:MM, e.g. 17:30.
         */
        closes: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Cities and regions the brokerage covers.
   */
  areaServed?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Square or wide logo used as the organization logo.
   */
  logo?: (number | null) | Media;
  /**
   * Fallback social card for pages without their own image.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Absolute URLs to official profiles (Facebook, Instagram, LinkedIn, Zillow, Google Business Profile).
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  brandHomeLink: {
    label: string;
    type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
    page?: (number | null) | Page;
    /**
     * Use a single-leading-slash app route or an HTTP(S) URL.
     */
    customUrl?: string | null;
    /**
     * Examples: #lead, /#lead.
     */
    anchor?: string | null;
    phone?: string | null;
    email?: string | null;
    newTab?: boolean | null;
    ariaLabel?: string | null;
  };
  /**
   * Text renders the house mark + brandLabel wordmark. Logo renders the Brand logo image instead. brandLabel / brandMarkAlt always remain the link’s accessible name, in either mode.
   */
  brandDisplayMode: 'text' | 'logo';
  brandLabel: string;
  brandMarkAlt?: string | null;
  brandLogo?: {
    /**
     * Shown only when Brand display mode is Logo.
     */
    image?: (number | null) | Media;
    /**
     * Optional. Falls back to the media alt text.
     */
    altOverride?: string | null;
  };
  navItems?:
    | {
        label: string;
        link: {
          label: string;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use a single-leading-slash app route or an HTTP(S) URL.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        ariaLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  primaryCta: {
    label: string;
    link: {
      label?: string | null;
      type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
      page?: (number | null) | Page;
      /**
       * Use a single-leading-slash app route or an HTTP(S) URL.
       */
      customUrl?: string | null;
      /**
       * Examples: #lead, /#lead.
       */
      anchor?: string | null;
      phone?: string | null;
      email?: string | null;
      newTab?: boolean | null;
      ariaLabel?: string | null;
    };
    ariaLabel?: string | null;
  };
  mobileMenuLabel: string;
  mobileMenuCloseLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brandName: string;
  /**
   * Text renders brandName + brandAccentText. Logo renders the Brand logo image instead. brandName always remains the fallback alt text.
   */
  brandDisplayMode: 'text' | 'logo';
  brandAccentText?: string | null;
  brandLogo?: {
    /**
     * Shown only when Brand display mode is Logo.
     */
    image?: (number | null) | Media;
    /**
     * Optional. Falls back to the media alt text.
     */
    altOverride?: string | null;
  };
  brandBlurb: string;
  columns?:
    | {
        title: string;
        /**
         * Auto columns list community Areas, so a new community appears here without editing the footer.
         */
        source: 'manual' | 'communities';
        links?:
          | {
              label: string;
              link: {
                label: string;
                type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
                page?: (number | null) | Page;
                /**
                 * Use a single-leading-slash app route or an HTTP(S) URL.
                 */
                customUrl?: string | null;
                /**
                 * Examples: #lead, /#lead.
                 */
                anchor?: string | null;
                phone?: string | null;
                email?: string | null;
                newTab?: boolean | null;
                ariaLabel?: string | null;
              };
              ariaLabel?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * How many communities to list, ordered by name.
         */
        communityLimit?: number | null;
        /**
         * Leave empty to auto-list by name. Set to pin an exact subset and order (ignores the limit above).
         */
        communityOverrides?: (number | Area)[] | null;
        id?: string | null;
      }[]
    | null;
  bottomLeftText: string;
  bottomRightLinks?:
    | {
        link: {
          label: string;
          type: 'internal' | 'custom' | 'anchor' | 'phone' | 'email';
          page?: (number | null) | Page;
          /**
           * Use a single-leading-slash app route or an HTTP(S) URL.
           */
          customUrl?: string | null;
          /**
           * Examples: #lead, /#lead.
           */
          anchor?: string | null;
          phone?: string | null;
          email?: string | null;
          newTab?: boolean | null;
          ariaLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  bottomRightTextFallback?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The published privacy policy at /privacy-policy. Have counsel review changes before saving — this is a legal disclosure, not marketing copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  title: string;
  /**
   * Shown under the title. Update it whenever the policy text changes.
   */
  lastUpdated?: string | null;
  /**
   * Optional lead paragraph, rendered above the policy body.
   */
  intro?: string | null;
  /**
   * Use headings for each section; lists and links are supported.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Leave blank to fall back to the policy title and intro.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalMode?: ('auto' | 'custom') | null;
    canonicalUrl?: string | null;
    index?: boolean | null;
    follow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    ogImageAlt?: string | null;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (number | null) | Media;
    twitterImageAlt?: string | null;
    /**
     * Uncheck to keep this URL out of /sitemap.xml.
     */
    includeInSitemap?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  description?: T;
  licenseNumber?: T;
  priceRange?: T;
  phone?: T;
  email?: T;
  address?:
    | T
    | {
        streetAddress?: T;
        addressLocality?: T;
        addressRegion?: T;
        postalCode?: T;
        addressCountry?: T;
      };
  geo?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  openingHours?:
    | T
    | {
        days?: T;
        opens?: T;
        closes?: T;
        id?: T;
      };
  areaServed?:
    | T
    | {
        value?: T;
        id?: T;
      };
  logo?: T;
  defaultOgImage?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  brandHomeLink?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        customUrl?: T;
        anchor?: T;
        phone?: T;
        email?: T;
        newTab?: T;
        ariaLabel?: T;
      };
  brandDisplayMode?: T;
  brandLabel?: T;
  brandMarkAlt?: T;
  brandLogo?:
    | T
    | {
        image?: T;
        altOverride?: T;
      };
  navItems?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
        id?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        ariaLabel?: T;
      };
  mobileMenuLabel?: T;
  mobileMenuCloseLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandName?: T;
  brandDisplayMode?: T;
  brandAccentText?: T;
  brandLogo?:
    | T
    | {
        image?: T;
        altOverride?: T;
      };
  brandBlurb?: T;
  columns?:
    | T
    | {
        title?: T;
        source?: T;
        links?:
          | T
          | {
              label?: T;
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    customUrl?: T;
                    anchor?: T;
                    phone?: T;
                    email?: T;
                    newTab?: T;
                    ariaLabel?: T;
                  };
              ariaLabel?: T;
              id?: T;
            };
        communityLimit?: T;
        communityOverrides?: T;
        id?: T;
      };
  bottomLeftText?: T;
  bottomRightLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              customUrl?: T;
              anchor?: T;
              phone?: T;
              email?: T;
              newTab?: T;
              ariaLabel?: T;
            };
        id?: T;
      };
  bottomRightTextFallback?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  intro?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalMode?: T;
        canonicalUrl?: T;
        index?: T;
        follow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogImageAlt?: T;
        twitterCard?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        twitterImageAlt?: T;
        includeInSitemap?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncBridgeListings".
 */
export interface TaskSyncBridgeListings {
  input: {
    trigger: 'cron' | 'manual';
    areaSlug?: string | null;
    full?: boolean | null;
  };
  output: {
    syncLogId: string;
    status: 'success' | 'warning' | 'error';
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskMirrorListingHero".
 */
export interface TaskMirrorListingHero {
  input: {
    listingId: string;
  };
  output: {
    skipped: boolean;
    mediaId?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncLeadToWiseAgent".
 */
export interface TaskSyncLeadToWiseAgent {
  input: {
    leadId: string;
  };
  output: {
    status: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}