#!/usr/bin/env bash
#
# init-project.sh — turn this template into a new project.
#
# Renames the package scope (@app/* -> @<scope>/*), updates the local Postgres
# identifiers, creates per-app .env.local files, and generates a Payload secret.
# Run ONCE, right after creating a repo from this template.
#
# Usage:
#   ./scripts/init-project.sh <scope> [db-name] [--git]
#
#   <scope>     npm-style package scope (lowercase). e.g. "acme" -> @acme/*
#   [db-name]   optional Postgres db/user/name. defaults to <scope>.
#   --git       re-initialise git with a single fresh commit (drops history).
#
# Examples:
#   ./scripts/init-project.sh acme
#   ./scripts/init-project.sh mvp-realty mvprealty --git
#
set -euo pipefail

die() { printf '\033[31merror:\033[0m %s\n' "$1" >&2; exit 1; }
info() { printf '\033[36m›\033[0m %s\n' "$1"; }
ok() { printf '\033[32m✓\033[0m %s\n' "$1"; }

# --- parse args -------------------------------------------------------------
SCOPE=""; DB=""; FRESH_GIT=0
for arg in "$@"; do
  case "$arg" in
    --git) FRESH_GIT=1 ;;
    -*)    die "unknown flag: $arg" ;;
    *)     if [ -z "$SCOPE" ]; then SCOPE="$arg"; elif [ -z "$DB" ]; then DB="$arg"; fi ;;
  esac
done
[ -n "$SCOPE" ] || die "missing <scope>. usage: ./scripts/init-project.sh <scope> [db-name] [--git]"
DB="${DB:-$SCOPE}"

# --- validate ---------------------------------------------------------------
echo "$SCOPE" | grep -Eq '^[a-z0-9][a-z0-9-]*$' || die "scope must be lowercase letters, numbers, hyphens: got '$SCOPE'"
echo "$DB"    | grep -Eq '^[a-z0-9][a-z0-9_-]*$' || die "db-name must be lowercase alphanumeric/_/-: got '$DB'"
[ "$SCOPE" != "app" ] || die "scope 'app' is the template default — pick a project-specific name"

# --- must run from repo root ------------------------------------------------
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
[ -f package.json ] && [ -f pnpm-workspace.yaml ] || die "run from the repo root (package.json + pnpm-workspace.yaml not found)"
grep -q '"@app/' package.json apps/*/package.json 2>/dev/null || die "template already initialised (no @app/* scope found) — nothing to do"

info "scope:   @app/*  ->  @$SCOPE/*"
info "db:      app     ->  $DB"
[ "$FRESH_GIT" -eq 1 ] && info "git:     re-init with a single fresh commit"
echo

# --- 1. rename package scope across all text files --------------------------
# grep -I skips binaries; exclude the lockfile (regenerated by pnpm) and this script.
SCOPE_COUNT=$(grep -rIl --exclude-dir=.git --exclude-dir=node_modules \
  --exclude=pnpm-lock.yaml --exclude=init-project.sh '@app/' . | wc -l | tr -d ' ')
grep -rIl --exclude-dir=.git --exclude-dir=node_modules \
  --exclude=pnpm-lock.yaml --exclude=init-project.sh '@app/' . \
  | while IFS= read -r f; do perl -i -pe "s{\@app/}{\@$SCOPE/}g" "$f"; done
ok "renamed @app/* -> @$SCOPE/* in $SCOPE_COUNT file(s)"

# --- 2. root package.json name ---------------------------------------------
perl -i -pe 's/^(\s*"name":\s*)"app"(,?)/$1"'"$SCOPE"'"$2/ if $. <= 3' package.json
ok "root package name -> \"$SCOPE\""

# --- 3. local Postgres identifiers -----------------------------------------
# docker-compose.yml: 'app' appears only as the project/db/user/container token.
perl -i -pe "s/\bapp\b/$DB/g" docker-compose.yml
# connection string wherever it appears (.env.example, README, docs)
grep -rIl --exclude-dir=.git --exclude-dir=node_modules \
  --exclude=init-project.sh 'postgres://app:app@localhost:5434/app' . \
  | while IFS= read -r f; do perl -i -pe "s{postgres://app:app\@localhost:5434/app}{postgres://$DB:$DB\@localhost:5434/$DB}g" "$f"; done
ok "postgres identifiers -> $DB (db/user/password)"

# --- 4. env files + Payload secret -----------------------------------------
SECRET="$(openssl rand -hex 32)"
for app in web backend; do
  if [ -f "apps/$app/.env.local" ]; then
    info "apps/$app/.env.local already exists — left untouched"
  else
    cp .env.example "apps/$app/.env.local"
  fi
done
# inject the generated secret into the backend env if it still has the placeholder
if grep -q 'replace-with-openssl-rand-base64-32' apps/backend/.env.local 2>/dev/null; then
  perl -i -pe "s/replace-with-openssl-rand-base64-32/$SECRET/" apps/backend/.env.local
fi
ok "wrote apps/web/.env.local + apps/backend/.env.local (with a fresh PAYLOAD_SECRET)"

# --- 5. optional fresh git --------------------------------------------------
if [ "$FRESH_GIT" -eq 1 ]; then
  rm -rf .git
  git init -q
  git add -A
  git commit -q -m "Initial commit — $SCOPE (from nextjs-payload-template)"
  ok "git re-initialised with a single commit"
fi

# --- done -------------------------------------------------------------------
echo
ok "project '$SCOPE' is ready."
cat <<EOF

next steps:
  nvm install && nvm use     # Node 24 (required)
  pnpm install               # installs deps + regenerates pnpm-lock.yaml
  pnpm dev                   # Postgres + web(:3000) + backend(:3001)

  then open http://localhost:3001/admin to create your first admin user.

note: this script is one-shot. you can delete scripts/init-project.sh now.
EOF
